trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  aliyunRegistry: 'registry.cn-hangzhou.aliyuncs.com'  # 替换为你的阿里云仓库地址
  aliyunRepo: 'matr1x/atec'               # 替换为你的命名空间和镜像名
  fullImageName: '$(aliyunRegistry)/$(aliyunRepo):$(tag)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and Push to Aliyun ACR
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(fullImageName)

    - script: |
        echo $(ALIYUN_ACR_PASSWORD) | docker login $(aliyunRegistry) \
          --username=$(ALIYUN_ACR_USERNAME) \
          --password-stdin
      displayName: 'Login to Aliyun ACR'
      env:
        ALIYUN_ACR_USERNAME: $(ALIYUN_ACR_USERNAME)
        ALIYUN_ACR_PASSWORD: $(ALIYUN_ACR_PASSWORD)

    - script: |
        docker push $(fullImageName)
      displayName: 'Push image to Aliyun ACR'