name: Build and Push Docker Image to Aliyun

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Aliyun Docker Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        
    # - name: Aggressive cleanup
    #   run: |
    #     # Remove Java (JDKs)
    #     sudo rm -rf /usr/lib/jvm
    
    #     # Remove .NET SDKs
    #     sudo rm -rf /usr/share/dotnet
    
    #     # Remove Swift toolchain
    #     sudo rm -rf /usr/share/swift
    
    #     # Remove Haskell (GHC)
    #     sudo rm -rf /usr/local/.ghcup
    
    #     # Remove Julia
    #     sudo rm -rf /usr/local/julia*
    
    #     # Remove Android SDKs
    #     sudo rm -rf /usr/local/lib/android
    
    #     # Remove Chromium (optional if not using for browser tests)
        # sudo rm -rf /usr/local/share/chromium
    
        # # Remove Microsoft/Edge and Google Chrome builds
        # sudo rm -rf /opt/microsoft /opt/google
    
        # # Remove Azure CLI
        # sudo rm -rf /opt/az
    
        # # Remove PowerShell
        # sudo rm -rf /usr/local/share/powershell
    
        # # Remove CodeQL and other toolcaches
        # sudo rm -rf /opt/hostedtoolcache
    
        # docker system prune -af || true
        # docker builder prune -af || true
        # df -h

    # - name: Install dependencies
    #   run: |
    #     pip install -U huggingface_hub hf-transfer
        
    # - name: Download model
    #   env:
    #     HF_HUB_ENABLE_HF_TRANSFER: 1
    #   run: |
    #     huggingface-cli download --resume-download Qwen/Qwen2.5-7B --local-dir ./user-model-v3
    #     df -h

    # - name: Move model to /mnt/model
    #   run: |
    #     sudo mv ./user-model-v3 /mnt/model
    #     sudo chmod -R a+rx /mnt/model
    #     df -h

    - name: Build and push Docker image
      uses: docker/build-push-action@v5   # 需要 v5 才支持 build-contexts
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/matr1x/atec:${{github.sha}}
        # build-contexts: |
        #   model=/mnt/model
          
    - name: Logout of Aliyun Docker Registry
      run: docker logout registry.cn-hangzhou.aliyuncs.com
