name: Build and Push Docker Image to Aliyun

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Aliyun Docker Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/matr1x/atec:${{github.sha}}

    - name: Logout of Aliyun Docker Registry
      run: docker logout registry.cn-hangzhou.aliyuncs.com
